### ISSUE TITLE
How is the HW connected?

### ISSUE THREAD

**Issue by tofferlicious** [Izumemori/esphome_vs481b#1]
First of all, great project!
I was trying to actually achieve something much simpler through Arduino code, but I cannot get any reaction from the VS481B at all...

Could you please let me know, how you connected it? Did you use an RS232 to TTL converter like the MAX3232?
Vielen Dank im Voraus 👍

**Comment by Izumemori** [comment]
The uart configuration I'm using for my deployed ESP is 
```yaml
uart:
  baud_rate: 19200
  tx_pin: 
    number: 16
    inverted: false
  rx_pin: 
    number: 17
    inverted: false
  data_bits: 8
  stop_bits: 1
  parity: NONE
```
and I use a MAX3232 to convert from TTL to RS232.
